#ifndef CHARTER_MUSIC_BROWSER_RESOURCE_H
#define CHARTER_MUSIC_BROWSER_RESOURCE_H

#define IDI_APP_ICON 101
#define IDI_HOME_ICON 201
#define IDI_DOWNLOADS_ICON 202
#define IDI_SETTINGS_ICON 203
#define IDI_FOLDER_ICON 204
#define IDI_ADD_ICON 205
#define IDI_TRASH_ICON 206
#define IDI_PENCIL_ICON 207
#define IDI_SEARCH_ICON 208
#define IDI_DOWNLOAD_ICON 209
#define IDI_SAVE_ICON 210
#define IDI_CLOSE_ICON 211
#define IDI_REFRESH_ICON 212
#define IDI_LOOP_ICON 213
#define IDI_SHUFFLE_ICON 214
#define IDI_STAR_ICON 215
#define IDI_HEART_ICON 216
#define IDI_MUTE_ICON 217
#define IDI_MUSICAL_ICON 218
#define IDI_YOUTUBE_ICON 219

#endif
